[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/agent-api/"
  to = "/agent-api/v0.2/"
  status = 200
  force = false

[[redirects]]
  from = "/customer-api/"
  to = "/customer-api/v0.2/"
  status = 200
  force = false