baseurl = "/docs/"
languageCode = "en-us"
title = "chat.io/docs"
disableHugoGeneratorInject = true

[[redirects]]
  from = "/docs/agent-api*"
  to = "/docs/agent-api/v0.2:splat"
  status = 200
  force = false

[[redirects]]
  from = "/docs/customer-api"
  to = "/docs/customer-api/v0.2"
  status = 200
  force = false